# Generated by Django 4.2.7 on 2023-11-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="image",
            field=models.URLField(max_length=255),
        ),
    ]
